<a href="https://colab.research.google.com/github/kamakshi66/kamakshi/blob/main/BASIC_ML_DAY1_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_array=np.array([1,5,90,45])
print(arr_array)
print(type(arr_array))

[ 1  5 90 45]
<class 'numpy.ndarray'>


In [ ]:
arr_arange=np.arange(1,11)
print(arr_arange)
print(type(arr_arange))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
arr_linspc=np.linspace(1,11)
print(arr_linspc)
print(type(arr_linspc))

[ 1.          1.20408163  1.40816327  1.6122449   1.81632653  2.02040816
  2.2244898   2.42857143  2.63265306  2.83673469  3.04081633  3.24489796
  3.44897959  3.65306122  3.85714286  4.06122449  4.26530612  4.46938776
  4.67346939  4.87755102  5.08163265  5.28571429  5.48979592  5.69387755
  5.89795918  6.10204082  6.30612245  6.51020408  6.71428571  6.91836735
  7.12244898  7.32653061  7.53061224  7.73469388  7.93877551  8.14285714
  8.34693878  8.55102041  8.75510204  8.95918367  9.16326531  9.36734694
  9.57142857  9.7755102   9.97959184 10.18367347 10.3877551  10.59183673
 10.79591837 11.        ]
<class 'numpy.ndarray'>


In [ ]:
arr_one=np.ones((3,3),dtype=int)
print(arr_one)
print(type(arr_one))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>


In [ ]:
arr_zero=np.zeros((3,3))
print(arr_zero)
print(type(arr_zero))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
arr_array=np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(arr_array)
print(type(arr_array))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
my_cgpa=np.random.randint(1,13,3)
frnd_cgpa=np.random.randint(1,13,3)
sem = np.arange(1,9)
print(type(my_cgpa))
print(my_cgpa)

<class 'numpy.ndarray'>
[11 12  5]


In [ ]:
np.mean(my_cgpa)

8.666666666666666

In [ ]:
np.mean(frnd_cgpa)

8.666666666666666

In [ ]:
np.average(sem)

4.5

In [ ]:
np.shape(my_cgpa)

(3,)

In [ ]:
print(arr_array.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
print(arr_array.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.mean(my_cgpa))
print(np.average(sem))

9.333333333333334
4.5


In [ ]:
names=['jin','jimin','jhope','jk','v','rm','suga']
names=np.random.choice(names,60)
names

array(['jimin', 'jk', 'suga', 'jk', 'jk', 'v', 'jhope', 'jk', 'jhope',
       'v', 'jk', 'jimin', 'jimin', 'suga', 'v', 'suga', 'rm', 'jimin',
       'jimin', 'jimin', 'suga', 'v', 'suga', 'jk', 'jin', 'jimin', 'rm',
       'rm', 'v', 'rm', 'jimin', 'v', 'jhope', 'jhope', 'jin', 'jin',
       'suga', 'jimin', 'jimin', 'rm', 'v', 'rm', 'jk', 'suga', 'jhope',
       'v', 'jimin', 'jimin', 'v', 'jk', 'jhope', 'jk', 'jin', 'suga',
       'jimin', 'jhope', 'jhope', 'v', 'rm', 'suga'], dtype='<U5')

In [2]:
import numpy as np
import pandas as pd
import random
names=['tom','jerry','nick','john','kam']
names=np.random.choice(names,500)
unqiue_id=random.sample(range(100,9999),500)
gender =np.random.choice(['male','female',np.NaN],500)
age=np.random.choice(range(18,80),500)
salary = np.random.randint(15000,200000,500)
Credict_score = np.random.randint(1,11,500)
purchased = np.random.choice(['YES','NO'])




In [3]:
data = {
    'UNQIUE_ID':unqiue_id,
    'NAME':names,
    'GENDER':gender,
    'AGE':age,
    'SALARY':salary,
    'CREDICT_SCORE':Credict_score,
    'PURCHASED':purchased
}
df=pd.DataFrame(data)
print(df)



     UNQIUE_ID   NAME  GENDER  AGE  SALARY  CREDICT_SCORE PURCHASED
0         6305  jerry  female   54  196046              9       YES
1         8567    tom    male   56   19114              4       YES
2         9362  jerry     nan   49  197256              7       YES
3         5217    kam  female   79  102470              9       YES
4         4749   nick  female   27  139683              3       YES
..         ...    ...     ...  ...     ...            ...       ...
495       5469   nick  female   68   23321              8       YES
496       7538   john  female   48   26734              1       YES
497       4460   nick    male   48  198254              7       YES
498       9342   john     nan   67   59491              6       YES
499       1912   nick    male   45   50950              8       YES

[500 rows x 7 columns]


In [4]:
df.head(2)


UNQIUE_ID   NAME  GENDER  AGE  SALARY  CREDICT_SCORE PURCHASED
0       6305  jerry  female   54  196046              9       YES
1       8567    tom    male   56   19114              4       YES

In [5]:
df.tail()


UNQIUE_ID  NAME  GENDER  AGE  SALARY  CREDICT_SCORE PURCHASED
495       5469  nick  female   68   23321              8       YES
496       7538  john  female   48   26734              1       YES
497       4460  nick    male   48  198254              7       YES
498       9342  john     nan   67   59491              6       YES
499       1912  nick    male   45   50950              8       YES

In [6]:
df.describe(include='all')

UNQIUE_ID NAME GENDER         AGE         SALARY  CREDICT_SCORE  \
count    500.000000  500    500  500.000000     500.000000     500.000000   
unique          NaN    5      3         NaN            NaN            NaN   
top             NaN  tom    nan         NaN            NaN            NaN   
freq            NaN  112    171         NaN            NaN            NaN   
mean    4956.602000  NaN    NaN   50.208000  105397.950000       5.614000   
std     2888.147875  NaN    NaN   17.158017   53137.088815       2.827188   
min      129.000000  NaN    NaN   18.000000   15832.000000       1.000000   
25%     2342.000000  NaN    NaN   36.000000   62240.250000       3.000000   
50%     4887.500000  NaN    NaN   50.000000  106834.500000       6.000000   
75%     7493.500000  NaN    NaN   65.000000  149674.000000       8.000000   
max     9979.000000  NaN    NaN   79.000000  199432.000000      10.000000   

       PURCHASED  
count        500  
unique         1  
top          YES  
freq         500  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [7]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   UNQIUE_ID      500 non-null    int64 
 1   NAME           500 non-null    object
 2   GENDER         500 non-null    object
 3   AGE            500 non-null    int64 
 4   SALARY         500 non-null    int64 
 5   CREDICT_SCORE  500 non-null    int64 
 6   PURCHASED      500 non-null    object
dtypes: int64(4), object(3)
memory usage: 27.5+ KB
